package io.github.aasaru.drools.section03.step3

import io.github.aasaru.drools.domain.NewPassport;

rule "Valid passport"
  dialect "java"
  when
	$passport: NewPassport( !isExpired(), $unusedPages: unusedVisaPages > 0 )
  then
	System.out.println( $passport + " is CORRECT. It has " + $unusedPages + " pages free." );
end

rule "Expired passport"
  dialect "java"
  when
	$passport: NewPassport( isExpired() )
  then
	System.out.println( $passport + " is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	$passport: NewPassport( unusedVisaPages == 0 )
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );
end
