package io.github.aasaru.drools.section08.step5

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.LoggingUtil;


rule "Everyone is at least 10"
	when
		forall (Passport(age >= 10))
	then
		LoggingUtil.info("Everyone whose passport is in session is at least 10 years old");
end
