package io.github.aasaru.drools.section03.step2

import io.github.aasaru.drools.domain.NewPassport;

rule "Valid passport"
  dialect "java"
  when
	NewPassport( !isExpired(), unusedVisaPages > 0 )
  then
	System.out.println( "This passport is CORRECT" );
end

rule "Expired passport"
  dialect "java"
  when
	NewPassport( isExpired() )
  then
	System.out.println( "This passport is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	NewPassport( unusedVisaPages == 0 )
  then
	System.out.println( "This passport is INVALID because it has no space for visa" );
end
