package io.github.aasaru.drools.section08.step1

import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;
import io.github.aasaru.drools.LoggingUtil;

rule "Invalidate visa applications with invalid passport"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		// not (InvalidFamilyVisaApplication(familyVisaApplication == $familyVisaApplication))
		InvalidPassport($familyVisaApplication.passportNumbers.contains(this.passport.passportNumber))
	then
		LoggingUtil.info( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert(new InvalidFamilyVisaApplication($familyVisaApplication));
end
