package io.github.aasaru.drools.section08.step1

import io.github.aasaru.drools.domain.InvalidFamilyVisaApplication;
import io.github.aasaru.drools.domain.FamilyVisaApplication;
import io.github.aasaru.drools.domain.Visa;
import io.github.aasaru.drools.LoggingUtil;

rule "Issue visas for valid applications"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		not (InvalidFamilyVisaApplication( this.familyVisaApplication == $familyVisaApplication))
	then
		for (String passportNumber : $familyVisaApplication.getPassportNumbers()) {
		  LoggingUtil.info( "Issue visa for passport number " + passportNumber);
		  insertLogical(new Visa( passportNumber));
		}
end
