package io.github.aasaru.drools.section08.step1
 
import io.github.aasaru.drools.domain.InvalidPassport;
import io.github.aasaru.drools.domain.Passport;

rule "Expired passport"
	when
		$passport: Passport(isExpired())
	then
		LoggingUtil.info($passport + " is INVALID because it is expired");
		insert(new InvalidPassport($passport));
end

rule "Full passport"
	when
		$passport: Passport(unusedVisaPages == 0)
	then
		LoggingUtil.info( $passport + " is INVALID because it has no space for visa" );
		insert(new InvalidPassport($passport));
end
